### PR TITLE
Translations to Spanish & Portuguese

### PR DESCRIPTION
**Pull request by tjaoc**
# Contribution checklist

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [] - Does a local formatting is applied (rush format)
* [ ] - Does a local svelte-check is applied (rush svelte-check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [X] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [X] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

## Contributor requirements

* [X] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [ ] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

### CODE REVIEW

**Comment by haiodo** [comment]
Hi @tjaoc thanks for more translations,  unfortunately we need to name translation file by just two letters, so I've changed in my previous PR to main. 

Could you please check and rename if possible, to prevent potential conflicts.
Thanks a lot.

**Comment by tjaoc** [comment]
Hello @haiodo, the reason I put it that way is because there is, for example, Spanish from Spain and Spanish from other countries such as Mexico, Argentina, etc., just as there is Portuguese from Portugal, Brazil, Angola, etc. And I follow ISO rules like in this list https://gist.github.com/eddieoz/63d839c8a20ef508cfa4fa9562632a21. But I have no problem changing it, if so, please let me know.

**Comment by aplatoff** [comment]
> Hello @haiodo, the reason I put it that way is because there is, for example, Spanish from Spain and Spanish from other countries such as Mexico, Argentina, etc., just as there is Portuguese from Portugal, Brazil, Angola, etc. And I follow ISO rules like in this list https://gist.github.com/eddieoz/63d839c8a20ef508cfa4fa9562632a21. But I have no problem changing it, if so, please let me know.

Hi @tjaoc! You're absolutely right about ISO rules and language variants, but it's our bad -- we did not support ISO approach for now, and use only two letters to identify language without variants support. Maybe in the future :) For now, having just two letters for translation is the best way to support translation files.

Thank you again for your awesome help and efforts! 👍

**Comment by tjaoc** [comment]
I am finishing the translations of the entire application. I have translated into all existing "lang" folders. Now when there are changes, please inform me so I can update those files or if new ones appear.

**Review by haiodo — APPROVED** [review]

**Pull request merged**
