### PR TITLE
Tags: Fix collection editor

### PR DESCRIPTION
**Pull request by annano**
Signed-off-by: Anna No <anna.no@xored.com>

# Contribution checklist

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [x] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [x] - Does the translations are up to date?
* [x] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [x] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [x] - Is there any redundant or duplicate code?
* [x] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

### CODE REVIEW

**Review by BykhovDenis — COMMENTED** [review]
May be we should have `AttribueEditor` and `CollectionEditor` for tags and use `allowedCollections` to choose?

**Comment by annano** [comment]
@BykhovDenis we are using `allowedCollections` Attribute bar and display tags collection as attribute in Board Card, but for Candidate skills (also tags collection) are displayed in editor view

**Comment by haiodo** [comment]
I think we should extend CollectionEditor to be following: 
```
interface CollectionEditor {
 component?: AnyComponent
 barComponent?: AnyComponent
}

So in case it is used from AttributeBar it should use barComponent if not it will use component instead.

Thoughts?

Also we do not need EditorViewMode.Attribute in this case.

**Comment by annano** [comment]
@haiodo added `inlineEditor` in https://github.com/hcengineering/anticrm/pull/2081

**Pull request closed without merging**
