### PR TITLE
fix: label data cleared when changing label color

### PR DESCRIPTION
**Pull request by chemarbraithwaite**
# Contribution checklist

## Brief description

A fix for the label title resetting when the color pop up is opened on creating a new tag/label.

See original issue here:

View in Huly [UBERF-6225](https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjA2YTQ2ZjlmYTE1ODMyNDcyOWY5MzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.wo743tmfWHhVQUISODUIi--0P3hTKuw7GxlAJUvvQu0)

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does a local formatting is applied (rush format)
* [ ] - Does a local svelte-check is applied (rush svelte-check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

#5093 

## Contributor requirements

* [ ] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [ ] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

### CODE REVIEW

**Comment by aplatoff** [comment]
Thank you. If you're really sure that `CreateTagElement` is used _only_ in `TagsPopup`, then good job. Looking ahead: the `platform` codebase is also used in other projects, so we can't be certain if someone else might be using something like `CreateTagElement` and its `title` property. So it's always safer to preserve names of properties in existing _public_ components, even if they could have better names :)

**Comment by aplatoff** [comment]
Also, please could you sign-off your PR? Please see `DCO` check failed for more information.

**Comment by chemarbraithwaite** [comment]
> Thank you. If you're really sure that `CreateTagElement` is used _only_ in `TagsPopup`, then good job. Looking ahead: the `platform` codebase is also used in other projects, so we can't be certain if someone else might be using something like `CreateTagElement` and its `title` property. So it's always safer to preserve names of properties in existing _public_ components, even if they could have better names :)

Noted! I updated the PR :) 👍🏿

**Comment by haiodo** [comment]
Hi @chemarbraithwaite, thanks for a contribution, but this is not a fully valid fix, since it not fixes problem source.
 I will fix in separate PR so we could close this one.

**Pull request closed without merging**
