### PR TITLE
[TSK-932] Show only diffs for description changes in activity

### PR DESCRIPTION
**Pull request by wazsone**
# Contribution checklist

## Brief description
image

## Related issues
https://front.hc.engineering/workbench/platform/tracker/TSK-932

## Checklist

* [ ] - UI test added to added/changed functionality?
* [x] - Screenshot is added to PR if applicable ?
* [x] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [x] - Does it well tested?
* [x] - Tested for Chrome.
* [x] - Tested for Safari.
* [x] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [x] - Is there any redundant or duplicate code?
* [x] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

### CODE REVIEW

**Review by haiodo — CHANGES_REQUESTED** [review]
@wazsone Let's show diff only if user press button(toggle), over wise just show what description is changed. So by default it will be minimal sized control. Thanks. Icon are not from here as well, so it should not be used. Thanks.

**Comment by wazsone** [comment]
@haiodo diff is hidden by default and is shown when toggle button pressed, on the screenshot I just expanded diffs to show different states. I have used here a diff show button icon. What icon I should use instead?

**Comment by wazsone** [comment]
@haiodo Thank you. Fixed

**Comment by wazsone** [comment]
@haiodo @BykhovDenis Could you please review this PR. I have done changes we discussed.

**Review by haiodo — APPROVED** [review]

**Pull request merged**
