### PR TITLE
Fix chat actions labels

### PR DESCRIPTION
**Pull request by kristina-fefelova**
Screenshot 2024-09-03 at 18 51 58 Screenshot 2024-09-03 at 18 52 04

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQ3MjVhMGFjY2U3NzU1MjYyZmQwZjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.oU8lFLwab_0wtroaPEwXwgTNzesjrUz5woJcv6_GDoY">Huly&reg;: <b>UBERF-8029</b></a></sub>

### CODE REVIEW

**Review by haiodo — DISMISSED** [review]

**Review by haiodo — APPROVED** [review]

**Comment by kakRostropovich** [comment]
[Kristina Fefelova](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=63204fc031b9728f9e6b2e1a&label=Kristina%20Fefelova), it looks like your changes does’nt fix menu name

I still see “Hide” instead “Leave channel“ in the channel menu

Check it please

**Comment by haiodo** [comment]
@kakRostropovich You need to specify there did you see it, since no new version is deployed.

**Comment by kakRostropovich** [comment]
Of course, I try to see it in local machine in develop branch. I see other changes from other pull request, and see Kristina’s change in the code, but I still see old labels

**Comment by kakRostropovich** [comment]
Everything is ok, upgrade -f solved that

**Pull request merged**
