### PR TITLE
Single z-index for tooltips and popups

### PR DESCRIPTION
**Pull request by ThetaDR**
Override zIndex for cases the popup opens from tooltip (ex.: comments)

image

### CODE REVIEW

**Review by haiodo — DISMISSED** [review]

**Comment by aonnikov** [comment]
to be honest, I don't like this approach. It is good as a temporary solution, but eventually overrides will produce more mess because we will have to manually manage all z-indexes.

Ideally, we need to get rid of library that is used in editor for popups and replace them with our popups. Alternatively, we can expose z-index counter or methods for accessing it and use it in text editor.

**Comment by haiodo** [comment]
I think we need unified z-layer order allocator between popups and tooltips.

**Comment by haiodo** [comment]
Or unify them under one place.

**Comment by ThetaDR** [comment]
Discussed with @aonnikov, going to use svelte `use` directive for it, it should make it more stable so it should prevent some of the bugs compared to this approach

**Pull request closed without merging**
