### PR TITLE
feat: resend invitation to kicked employee

### LINKED ISSUE #7151: [Feature Request]: Resend Invite link
### Description of the issue

Ability to resend invite link after link expires for employees

### Expected behavior

Admin should be able to resend invite link after link expires for employees

### Actual behavior

I do not find any option for resending invite link.

### PR DESCRIPTION
**Pull request by dakshesh14**
**Feature:**

- Added an option for users to extend the invitation validity for employees.
- Employees receive an email notification when their invitation validity is extended, informing them of the updated validity period.
- It can potentially fix #7151.

**Screenshots:**

Context Menu
context-menu

Confirmation Modal
confirmation-modal

### CODE REVIEW

**Comment by dakshesh14** [comment]
Hi team, I want to add a condition to show the 'Extend Invite' option only if the employee hasn't joined and their invitation validity has expired. This is important to avoid confusing UX. However, I'm having difficulty distinguishing between employees and invited employees in the current setup.

As an alternative, I could change the CTA to 'Resend Invite' and update the modal copy to suggest using this option if the link has broken or expired. I would love to hear your thoughts or suggestions on approaching this!

**Comment by haiodo** [comment]
Hi @dakshesh14 I suppose you could enable this action to send it for any Inactive employe, so in case of we kick someone, we will be able to resend invitation :-)

**Comment by dakshesh14** [comment]
Hi @haiodo, that’s a great suggestion! Currently, I’ve implemented the feature to extend the validity of existing invitations, but I’ll add support for re-inviting inactive (kicked) employees as well.

I was wondering if the expiration date of an invitation is available. This would allow me to show the 'Resend Invite' option only if the invitation has expired.

Also, do you happen to have any documentation or references for setting up SES locally for development? That would be super helpful!

**Comment by dakshesh14** [comment]
Hey @haiodo, I made all the changes. Can you review my PR?

**Review by haiodo — APPROVED** [review]

**Pull request merged**
