### PR TITLE
Improved collaborative cursor hover experience

### PR DESCRIPTION
**Pull request by aumkar**
**Pull Request Requirements:**

* Increased hover area for cursor so user can easily hover on it to see collaborator name.

Earlier:

https://github.com/hcengineering/platform/assets/8870974/ce106e62-8a35-499b-ac0e-c31630ab67e1

Now:

https://github.com/hcengineering/platform/assets/8870974/eed51715-87c6-4c40-9ed0-7ed28cf0bc5a

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjFkYmZkNWZiMTljMDhlYWJhZDg4ZjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.BwGztMaiGnRPDmydM82tSRFKcqPa2QJe8aHAxCOF8YA">Huly&reg;: <b>UBERF-6569</b></a></sub>

### CODE REVIEW

**Comment by aonnikov** [comment]
Hello! Thanks for the contribution.
I cannot open the video, but when I apply the changes locally, the arrow that should be above the cursor, not is displayed to the left of cursor. Can we change this?

**Comment by aumkar** [comment]
Yeah, right. I had seen it some times (in both newer and older implementation). I think its related to screen resolution since it works fine with zoomed in window.

I have added a change which should fix it for all cases.

**Comment by aonnikov** [comment]
Could you also sign-off your commits?

**Comment by aumkar** [comment]
@aonnikov I will raise another PR. I messed up while signing off commits before to `git pull`

**Comment by aonnikov** [comment]
not needed anymore

**Pull request closed without merging**
